apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: memcached-webhook-cert
spec:
  secretName: memcached-validating-webhook-certs
  dnsNames:
  - memcached-validating-webhook-svc.memcached.svc
  - memcached-validating-webhook-svc.memcached.svc.cluster.local
  issuerRef:
    name: ca-issuer