apiVersion: apps/v1
kind: Deployment
metadata:
  name: memcached-validating-webhook-deployment
  namespace: memcached
  labels:
    app: memcached-validating-webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: memcached-validating-webhook
  template:
    metadata:
      labels:
        app: memcached-validating-webhook
    spec:
      containers:
        - name: memcached-validating-webhook
          image: azssi/memcached-validating-webhook:latest
          imagePullPolicy: Always
          args:
          - -tlsCertFile=/etc/webhook/certs/tls.crt
          - -tlsKeyFile=/etc/webhook/certs/tls.key
          - -alsologtostderr
          - -v=4
          - 2>&1
          volumeMounts:
          - name: webhook-certs
            mountPath: /etc/webhook/certs
            readOnly: true
      volumes:
      - name: webhook-certs
        secret:
          secretName: memcached-validating-webhook-certs