apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: memcached-validating-webhook-cfg
  namespace: memcached
  labels:
    app: memcached-validating-webhook
  annotations:
    cert-manager.io/inject-ca-from: memcached/memcached-webhook-cert
webhooks:
- name: memcached-validating-webhook.tmax.io
  clientConfig:
    service:
      name: memcached-validating-webhook-svc
      namespace: memcached
      path: "/mutate"
  sideEffects: None
  timeoutSeconds: 5
  admissionReviewVersions:
    - v1
    - v1beta1
  rules:
  - operations: ["CREATE"]
    apiGroups: ["memcached.tmax.io"]
    apiVersions: ["v1alpha1"]
    resources: ["memcacheds"]
    scope: "Namespaced"
