apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: memcached-validating-webhook-cfg
  namespace: memcached
  labels:
    app: memcached-validating-webhook
  annotations:
    cert-manager.io/inject-ca-from: memcached/memcached-webhook-cert
webhooks:
- name: memcached-validating-webhook.tmax.io
  clientConfig:
    service:
      name: memcached-validating-webhook-svc.memcached.svc
      namespace: memcached
      path: "/mutate"
    # caBundle: ${CA_BUNDLE}
  rules:
  - operations: ["CREATE"]
    apiGroups: ["tmax.io"]
    apiVersions: ["v1alpha1"]
    resources: ["memcached"]
    scope: "Namespaced"
